using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using MoaiCode.Core.Tools;
using MoaiCode.Localization;

namespace MoaiCode.Tools.OpenXml;

/// <summary>새 Word 문서(.docx)를 만든다. Open XML SDK — Word 설치 불필요, 전 플랫폼.</summary>
public sealed class DocxCreateTool : ITool
{
    public string Name => "DocxCreate";

    public string Description => """
        Creates a new Word document (.docx) using the built-in Open XML writer — no dependencies,
        no Word install. ALWAYS use this to produce a .docx file. Do NOT install packages (npm 'docx',
        python-docx, etc.) or write Bash/Node/Python scripts to build Word files — this tool already
        does it. For a well-structured document, prefer 'blocks' (ordered mix of headings, paragraphs,
        bullet/numbered lists, and tables) over a flat 'paragraphs' array. Text in any block may use
        markdown-style **bold** and *italic*.
        DOCUMENT FORMS: set "template" to a Korean business doc type and produce the standard sections
        as heading blocks, filling each — report: overview, background, current status, analysis,
        conclusions and recommendations; incident: incident summary, sequence of events, cause,
        actions taken, recurrence-prevention measures; proposal: background and objectives, proposal
        details, expected effects, schedule, required budget.
        If you provide no blocks, the standard section skeleton is scaffolded for the user to fill.
        For editing an OPEN document on Windows, use the COM tools.
        """;

    public bool IsReadOnly => false;
    public bool IsConcurrencySafe => true;

    public JsonElement InputSchema { get; } = JsonDocument.Parse(
        """
        {
          "type": "object",
          "properties": {
            "path": { "type": "string", "description": "Output .docx path (relative to workspace)" },
            "template": { "type": "string", "enum": ["report", "incident", "proposal"], "description": "Korean business document form: report, incident, or proposal. Produce the standard sections as heading blocks (see tool description). If no blocks are given, the section skeleton is scaffolded." },
            "title": { "type": "string", "description": "Document title (large bold heading, first line)" },
            "blocks": {
              "type": "array",
              "description": "Ordered body content. Use this for structured documents (reports, letters). Each block is one of the types below.",
              "items": {
                "type": "object",
                "properties": {
                  "type": { "type": "string", "enum": ["heading", "paragraph", "bullets", "numbered", "table"], "description": "Block kind" },
                  "level": { "type": "integer", "description": "heading only: 1 (section) .. 3 (sub-sub). Default 1" },
                  "text": { "type": "string", "description": "heading/paragraph text. Supports **bold** and *italic*." },
                  "items": { "type": "array", "items": { "type": "string" }, "description": "bullets/numbered: list items. Supports **bold**/*italic*." },
                  "header": { "type": "boolean", "description": "table only: render the first row as a bold shaded header. Default true." },
                  "rows": { "type": "array", "items": { "type": "array", "items": { "type": "string" } }, "description": "table only: rows of cell text (row-major)." }
                },
                "required": ["type"]
              }
            },
            "paragraphs": { "type": "array", "items": { "type": "string" }, "description": "Flat body paragraphs. Ignored when 'blocks' is provided. Supports **bold**/*italic*." },
            "images": {
              "type": "array",
              "description": "Images to embed after the body (e.g. figures generated by ImageCreate).",
              "items": {
                "type": "object",
                "properties": {
                  "path": { "type": "string", "description": "Image file path (.png/.jpg, relative to workspace)" },
                  "caption": { "type": "string", "description": "Optional caption below the image" },
                  "widthInches": { "type": "number", "description": "Display width in inches (default 5)" }
                },
                "required": ["path"]
              }
            }
          },
          "required": ["path"]
        }
        """).RootElement.Clone();

    private sealed record ImageIn(
        [property: JsonPropertyName("path")] string? Path,
        [property: JsonPropertyName("caption")] string? Caption,
        [property: JsonPropertyName("widthInches")] double? WidthInches);

    private sealed record BlockIn(
        [property: JsonPropertyName("type")] string? Type,
        [property: JsonPropertyName("level")] int? Level,
        [property: JsonPropertyName("text")] string? Text,
        [property: JsonPropertyName("items")] List<string>? Items,
        [property: JsonPropertyName("header")] bool? Header,
        [property: JsonPropertyName("rows")] List<List<string>>? Rows);

    private sealed record Input(
        [property: JsonPropertyName("path")] string? Path,
        [property: JsonPropertyName("title")] string? Title,
        [property: JsonPropertyName("template")] string? Template,
        [property: JsonPropertyName("blocks")] List<BlockIn>? Blocks,
        [property: JsonPropertyName("paragraphs")] List<string>? Paragraphs,
        [property: JsonPropertyName("images")] List<ImageIn>? Images);

    // 문서 유형별 표준 섹션(양식). 모델이 blocks 로 이 구조를 채우고, 비어 있으면 스캐폴딩된다.
    private static string[]? FormSections(string? template) => template?.Trim().ToLowerInvariant() switch
    {
        "report" or "보고서" => new[] { "개요", "배경", "현황", "분석", "결론 및 제언" },
        "incident" or "경위서" => new[] { "발생 개요", "경위", "원인", "조치 사항", "재발 방지 대책" },
        "proposal" or "제안서" => new[] { "배경 및 목적", "제안 내용", "기대 효과", "추진 일정", "소요 예산" },
        _ => null,
    };

    public async IAsyncEnumerable<ToolProgress> ExecuteAsync(
        JsonElement input, ToolContext context, [EnumeratorCancellation] CancellationToken ct)
    {
        await Task.Yield();
        var inp = input.Deserialize<Input>();
        if (inp is null || string.IsNullOrWhiteSpace(inp.Path))
        {
            yield return new ToolOutput("DocxCreate: 'path' is required", IsError: true);
            yield break;
        }

        string full;
        string? error = null;
        try
        {
            full = OpenXmlPaths.ResolveForWrite(context.WorkingDirectory, inp.Path, ".docx");
            Write(full, inp, context.WorkingDirectory);
        }
        catch (Exception ex)
        {
            error = ex.Message;
            full = string.Empty;
        }

        var bodyCount = inp.Blocks?.Count ?? inp.Paragraphs?.Count ?? 0;
        yield return error is not null
            ? new ToolOutput(L10n.Get("tools.docxCreate.failed", error), IsError: true)
            : new ToolOutput(L10n.Get("tools.docxCreate.ok", full, bodyCount, inp.Images?.Count ?? 0));
    }

    private static void Write(string path, Input inp, string workingDir)
    {
        using var doc = WordprocessingDocument.Create(path, WordprocessingDocumentType.Document);
        var main = doc.AddMainDocumentPart();
        main.Document = new Document();
        var body = main.Document.AppendChild(new Body());

        // MoAI 고유 식별자를 심어 나중에 같은 대화로 되찾을 수 있게 한다(생성 문서 한정).
        doc.AddCustomFilePropertiesPart().Properties = OfficeDocId.Build(OfficeDocId.NewId());

        if (!string.IsNullOrWhiteSpace(inp.Title))
        {
            body.AppendChild(Heading(inp.Title!, 0)); // level 0 = 문서 제목(가장 큼)
        }

        // blocks 가 있으면 그것을 본문으로, 없으면 기존 paragraphs 경로(하위호환).
        if (inp.Blocks is { Count: > 0 })
        {
            foreach (var b in inp.Blocks)
            {
                AppendBlock(body, b);
            }
        }
        else if ((inp.Paragraphs?.Count ?? 0) == 0 && FormSections(inp.Template) is { } sections)
        {
            // 양식 스캐폴딩: 콘텐츠가 없으면 표준 섹션 뼈대(제목 + 안내 문단)를 채워 넣는다.
            foreach (var sec in sections)
            {
                body.AppendChild(Heading(sec, 1));
                body.AppendChild(BodyParagraph("(내용을 입력하세요)"));
            }
        }
        else
        {
            foreach (var p in inp.Paragraphs ?? new List<string>())
            {
                body.AppendChild(BodyParagraph(p ?? string.Empty));
            }
        }

        uint imgId = 1;
        foreach (var img in inp.Images ?? new List<ImageIn>())
        {
            if (string.IsNullOrWhiteSpace(img.Path))
            {
                continue;
            }

            var imgFull = OpenXmlPaths.ResolveForRead(workingDir, img.Path!);
            if (!File.Exists(imgFull))
            {
                throw new FileNotFoundException(L10n.Get("tools.docxCreate.imageNotFound", img.Path));
            }

            var width = img.WidthInches is > 0 ? img.WidthInches!.Value : 5.0;
            body.AppendChild(ImageEmbed.DocxImageParagraph(main, imgFull, width, imgId++));
            if (!string.IsNullOrWhiteSpace(img.Caption))
            {
                body.AppendChild(Caption(img.Caption!));
            }
        }
    }

    private static void AppendBlock(Body body, BlockIn b)
    {
        switch ((b.Type ?? "paragraph").Trim().ToLowerInvariant())
        {
            case "heading":
                body.AppendChild(Heading(b.Text ?? string.Empty, Math.Clamp(b.Level ?? 1, 1, 3)));
                break;
            case "bullets":
                foreach (var it in b.Items ?? new List<string>())
                {
                    body.AppendChild(ListItem(it ?? string.Empty, "•  "));
                }

                break;
            case "numbered":
                var n = 1;
                foreach (var it in b.Items ?? new List<string>())
                {
                    body.AppendChild(ListItem(it ?? string.Empty, $"{n++}.  "));
                }

                break;
            case "table":
                body.AppendChild(BuildTable(b.Rows ?? new List<List<string>>(), b.Header ?? true));
                break;
            default: // "paragraph"
                body.AppendChild(BodyParagraph(b.Text ?? string.Empty));
                break;
        }
    }

    // 제목/절 제목: 스타일 파트 없이 크기·굵기·간격으로 시각 표현(현재 도구 철학 유지).
    // level 0 = 문서 제목, 1..3 = 절 제목.
    private static Paragraph Heading(string text, int level)
    {
        var halfPt = level switch { 0 => 36, 1 => 30, 2 => 26, _ => 23 }; // 18/15/13/11.5pt
        var props = new ParagraphProperties(
            new SpacingBetweenLines { Before = level == 0 ? "0" : "240", After = "120" });
        var p = new Paragraph(props);
        foreach (var run in InlineRuns(text, bold: true, sizeHalfPt: halfPt))
        {
            p.AppendChild(run);
        }

        return p;
    }

    private static Paragraph BodyParagraph(string text)
    {
        var p = new Paragraph();
        foreach (var run in InlineRuns(text))
        {
            p.AppendChild(run);
        }

        return p;
    }

    // 목록 항목: 접두어(• / 1.) + 왼쪽 들여쓰기(0.25"). 진짜 numbering 파트 대신 시각 표현.
    private static Paragraph ListItem(string text, string prefix)
    {
        var props = new ParagraphProperties(new Indentation { Left = "360" });
        var p = new Paragraph(props);
        p.AppendChild(TextRun(prefix));
        foreach (var run in InlineRuns(text))
        {
            p.AppendChild(run);
        }

        return p;
    }

    private static Table BuildTable(List<List<string>> rows, bool header)
    {
        // tblBorders 요소 순서: top → left → bottom → right → insideH → insideV (스키마 강제).
        var props = new TableProperties(
            new TableWidth { Type = TableWidthUnitValues.Pct, Width = "5000" }, // 100%
            new TableBorders(
                new TopBorder { Val = BorderValues.Single, Size = 4, Color = "BFBFBF" },
                new LeftBorder { Val = BorderValues.Single, Size = 4, Color = "BFBFBF" },
                new BottomBorder { Val = BorderValues.Single, Size = 4, Color = "BFBFBF" },
                new RightBorder { Val = BorderValues.Single, Size = 4, Color = "BFBFBF" },
                new InsideHorizontalBorder { Val = BorderValues.Single, Size = 4, Color = "BFBFBF" },
                new InsideVerticalBorder { Val = BorderValues.Single, Size = 4, Color = "BFBFBF" }));
        var table = new Table(props);

        // tblGrid(열 정의)는 tblPr 뒤, 행 앞에 와야 valid. 열 수 = 최대 셀 수, 균등 폭.
        var cols = rows.Count == 0 ? 1 : rows.Max(r => r?.Count ?? 0);
        cols = Math.Max(cols, 1);
        var colW = (9360 / cols).ToString(); // 본문 가용폭 ~9360 twips 균등 분할
        var grid = new TableGrid();
        for (var c = 0; c < cols; c++)
        {
            grid.AppendChild(new GridColumn { Width = colW });
        }

        table.AppendChild(grid);

        for (var r = 0; r < rows.Count; r++)
        {
            var isHeader = header && r == 0;
            var row = new TableRow();
            foreach (var cell in rows[r] ?? new List<string>())
            {
                row.AppendChild(BuildCell(cell ?? string.Empty, isHeader));
            }

            table.AppendChild(row);
        }

        return table;
    }

    private static TableCell BuildCell(string text, bool isHeader)
    {
        // tcPr 요소 순서: shd(음영)가 tcMar(여백)보다 앞에 와야 valid.
        var cellProps = new TableCellProperties();
        if (isHeader)
        {
            cellProps.AppendChild(new Shading
            {
                Val = ShadingPatternValues.Clear, Fill = "F2F2F2", Color = "auto",
            });
        }

        cellProps.AppendChild(new TableCellMargin(
            new LeftMargin { Type = TableWidthUnitValues.Dxa, Width = "90" },
            new RightMargin { Type = TableWidthUnitValues.Dxa, Width = "90" }));

        var para = new Paragraph();
        foreach (var run in InlineRuns(text, bold: isHeader))
        {
            para.AppendChild(run);
        }

        return new TableCell(cellProps, para);
    }

    // 캡션: 이탤릭·가운데정렬.
    private static Paragraph Caption(string text)
    {
        var run = new Run();
        run.AppendChild(new RunProperties(new Italic()));
        run.AppendChild(new Text(text) { Space = SpaceProcessingModeValues.Preserve });
        return new Paragraph(new ParagraphProperties(new Justification { Val = JustificationValues.Center }), run);
    }

    private static Run TextRun(string text)
    {
        var run = new Run();
        run.AppendChild(new Text(text) { Space = SpaceProcessingModeValues.Preserve });
        return run;
    }

    private static readonly Regex InlineToken =
        new(@"(\*\*[^*]+\*\*|__[^_]+__|\*[^*]+\*|_[^_]+_)", RegexOptions.Compiled);

    // 마크다운식 **bold**/__bold__/*italic*/_italic_ 를 Word Run 으로 분할.
    // baseBold/sizeHalfPt 는 블록 기본 서식(제목·헤더셀 등)에 겹쳐 적용된다.
    private static IEnumerable<Run> InlineRuns(string text, bool bold = false, int? sizeHalfPt = null)
    {
        var runs = new List<Run>();
        var last = 0;

        void Emit(string segment, bool segBold, bool segItalic)
        {
            if (segment.Length == 0)
            {
                return;
            }

            var rp = new RunProperties();
            if (bold || segBold)
            {
                rp.AppendChild(new Bold());
            }

            if (segItalic)
            {
                rp.AppendChild(new Italic());
            }

            if (sizeHalfPt is int sz)
            {
                rp.AppendChild(new FontSize { Val = sz.ToString() });
                rp.AppendChild(new FontSizeComplexScript { Val = sz.ToString() });
            }

            var run = new Run();
            if (rp.HasChildren)
            {
                run.AppendChild(rp);
            }

            run.AppendChild(new Text(segment) { Space = SpaceProcessingModeValues.Preserve });
            runs.Add(run);
        }

        foreach (Match m in InlineToken.Matches(text))
        {
            if (m.Index > last)
            {
                Emit(text[last..m.Index], false, false);
            }

            var t = m.Value;
            if (t.StartsWith("**") || t.StartsWith("__"))
            {
                Emit(t[2..^2], true, false);
            }
            else
            {
                Emit(t[1..^1], false, true);
            }

            last = m.Index + m.Length;
        }

        if (last < text.Length)
        {
            Emit(text[last..], false, false);
        }

        // 빈 문자열이면 최소 하나의 빈 run 을 둬서 valid 문단 유지.
        if (runs.Count == 0)
        {
            Emit(string.Empty == text ? string.Empty : text, false, false);
            if (runs.Count == 0)
            {
                runs.Add(TextRun(string.Empty));
            }
        }

        return runs;
    }
}
