<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="MoaiCode.Core.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MoaiCode.Core\MoaiCode.Core.csproj" />
    <ProjectReference Include="..\MoaiCode.Localization\MoaiCode.Localization.csproj" />
    <ProjectReference Include="..\MoaiCode.Persistence\MoaiCode.Persistence.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Markdig" />
  </ItemGroup>
</Project>
